name: DefaultTestingEnvironment

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: windows-latest
    # Using double brackets and checking against a string is more robust  
    steps:
      - name: Run Testing Script
        if: runner.os == 'Linux'  
        run: echo "Voila!" && echo "${{runner.os}}"
      - name: FailSafe Check
        if: runner.os != 'Linux'
        run: echo "Windows"
